### ISSUE TITLE
The link to paper

### ISSUE THREAD

**Issue by Xuehao-Gao** [GestaltCogTeam/D2STGNN#1]
Hi,
    We can notice that your D2STGNN obtains better performance from the Tables in Readme file. But, we did not find the paper link of D2STDNN. Can you share it with us?

Best.

**Comment by zezhishao** [comment]
> Hi, We can notice that your D2STGNN obtains better performance from the Tables in Readme file. But, we did not find the paper link of D2STDNN. Can you share it with us?
> 
> Best.

Hi, thanks for your interest~
Our paper is now undergoing a major revision. It will probably last about a month or two, and the paper will be uploaded to this repo when the reviewing process is over.

**Comment by zezhishao** [comment]
Thanks for your interest and sorry for the delay~
Now, the paper is available [here](https://arxiv.org/abs/2206.09112).
