### ISSUE TITLE
question about dataset shuffle

### ISSUE THREAD

**Issue by wkq-wukaiqi** [GestaltCogTeam/D2STGNN#6]
https://github.com/zezhishao/D2STGNN/blob/github/dataloader/dataloader.py#L31
The DataLoader only shuffle train dataset in func `__init__`, is it need to be reshuffle every epoch, i. e.  call `self.shuffle()` in func `get_iterator()`?

**Comment by wkq-wukaiqi** [comment]
> https://github.com/zezhishao/D2STGNN/blob/github/dataloader/dataloader.py#L31 The DataLoader only shuffle train dataset in func `__init__`, is it need to be reshuffle every epoch, i. e. call `self.shuffle()` in func `get_iterator()`?

I refer to this code in my own project, and if not shuffled every round, it will result in a drop in final accuracy

**Comment by zezhishao** [comment]
The implementation in this repo uses the pipeline in [Graph WaveNet.](https://github.com/nnzhan/Graph-WaveNet)
And this repository is no longer maintained, I would recommend you to use [BasicTS](https://github.com/zezhishao/BasicTS) to reproduce D2STGNN and many other baselines based on a unified and fair pipeline.
