### ISSUE TITLE
The link of Google Drive is invalid.

### ISSUE THREAD

**Issue by Infinite-Approximation** [GestaltCogTeam/D2STGNN#8]
When I run `python main.py`, the program reported an error and displayed " [Errno 2] No such file or directory: 'output/dataloader_PEMS08.pkl'". So is this file in Google Drive? But the link of Google Drive is invalid and the files in BaiduNetdisk not contains 'dataloader_PEMS08.pkl'.

**Comment by zezhishao** [comment]
Hi, thank you for the reminder. The Google Drive link is indeed invalid, and I will fix it later. In the meantime, you can access the files through Baidu Netdisk, as both sources contain the same files.

It seems that you have set the 'load_pkl' parameter to `True` in the configuration. Please follow the instructions in the README file to preprocess the data and run the program accordingly.

However, I would *strongly* recommend using [BasicTS](https://github.com/GestaltCogTeam/BasicTS) to reproduce D2STGNN and many of the other baselines. This repository is no longer actively maintained.

**Comment by Infinite-Approximation** [comment]
> Hi, thank you for the reminder. The Google Drive link is indeed invalid, and I will fix it later. In the meantime, you can access the files through Baidu Netdisk, as both sources contain the same files.
> 
> It seems that you have set the 'load_pkl' parameter to `True` in the configuration. Please follow the instructions in the README file to preprocess the data and run the program accordingly.
> 
> However, I would _strongly_ recommend using [BasicTS](https://github.com/GestaltCogTeam/BasicTS) to reproduce D2STGNN and many of the other baselines. This repository is no longer actively maintained.

Thank you for your reply. I will try BasicTS later.
